#!/usr/bin/env bash

# My custom colortheme, based on eldritch
# Color light and dark variants obtained from this site, going 4 levels bright and dark:
# https://www.color-hex.com/color/f15c65

black_background=#181818 # Inactive tmux window
black_base=#212337
black_light=#363a4f # Active tmux window
black_var1=#232e3b
black_var2=#363a4f
black_var3=#31412c 

red_base=#f15c65
red_light=#f58c93 # errors
red_dark=#a84046
red_var1=#8e5c60
red_var2=#f0c6c6

green_base=#37f499
green_light=#73f7b7
green_dark=#26aa6b
green_var1=#648359
green_var2=#a6da95

yellow_base=#e9f941
yellow_light=#effa7a #warnings
yellow_dark=#a3ae2d
orange=#f5a97f

blue_base=#6a8df4
blue_light=#96aff7
blue_dark=#4a62aa
blue_var1=#536892
blue_var2=#b7bdf8

magenta_base=#f265b5
magenta_light=#f593cb
magenta_dark=#a9467e
magenta_var1=#765f93
MY_EYES=#F712FF

cyan_base=#04d1f9
cyan_light=#4fdefa
cyan_dark=#0292ae

white_base=#ebfafa
white_light=#b5cdeb # comments
white_var1=#6d7195
white_var2=#c6a0f6
white_var3=#cad3f5 # text
