#!/usr/bin/env bash

# WARNING: Do not comment on the same lines as the colors, such as "color=#a2a2a2 # comment". The colors will be read incorrectly by neovim if you do.

# My custom colortheme, based on eldritch
# Color light and dark variants obtained from this site, going 4 levels bright and dark:
# https://www.color-hex.com/color/f15c65

# Inactive tmux window
black_background=#020105
black_base=#2f2e39
# Active tmux window
black_light=#363a4f
black_var1=#12111c
black_var2=#16141f
black_var3=#2A2933

red_base=#eb6f92
# errors
red_light=#ebbcba
red_dark=#a44d66
red_var1=#8e5c60
red_var2=#f0c6c6

green_base=#72c982
green_light=#9cd9a7
green_dark=#4f8c5b
green_var1=#4f7453
green_var2=#6a9c78

yellow_base=#f6c177
# warnings
yellow_light=#f8d39f
yellow_dark=#ac8753
orange=#ea9d34

blue_base=#286983
blue_light=#6896a8
blue_dark=#1c495b
blue_var1=#536892
blue_var2=#b7bdf8
purple=#907aa9

magenta_base=#c4a7e7
magenta_light=#d5c1ee
magenta_dark=#d7827e
magenta_var1=#765f93
MY_EYES=#F712FF

cyan_base=#3e8fb0
cyan_light=#77b0c7
cyan_dark=#2b647b

pure_white=#e0def4
white_base=#ebfafa
white_light=#b5cdeb
grey=#a5afc2
white_var1=#9893a5
white_var2=#6e6a86
# comments
white_var3=#908caa
