#!/usr/bin/env bash

prompt="add"

[ $# -eq 0 ] && read -p "Describe the task: " description || description="$*"

read -p "Due date (YYYY-MM-DD): " dueDate
if [[ ! -z "$dueDate" ]]; then
    prompt+=" due:$dueDate+24h"
fi

read -p "Scheduled date (YYYY-MM-DD): " scheduledDate
if [[ ! -z "$scheduledDate" ]]; then
    prompt+=" scheduled:$scheduledDate"
fi

read -p "Priority (L,M,H): " priority
prompt+=" priority:$priority"
# read -p "Tags: " tags
# read -p "Projects: " projects
project=$(task rc.list.all.projects=1 _projects | fzf)
prompt+=" project:$project"

task $prompt "$description"

