#!/usr/bin/env bash

[ $# -eq 0 ] && read -p "Describe the task: " description || description="$*"
read -p "Due date (YYYY-MM-DD): " dueDate
read -p "Priority (L,M,H): " priority
# read -p "Tags: " tags
# read -p "Projects: " projects
project=$(task rc.list.all.projects=1 _projects | fzf)

task add due:"$dueDate"+24h priority:"$priority" project:"$project" "$description"

