#!/bin/bash

SCREENSHOT_FILE="${HOME}/Pictures/OCR/ocr-screenshot.png"

mkdir -p "${HOME}/Pictures/OCR"

[[ ! -f "$SCREENSHOT_FILE" ]] && touch "$SCREENSHOT_FILE"

if [[ $1 == "vert" ]] then
  scrot -s -o -f "$SCREENSHOT_FILE" -e 'tesseract -l jpn_vert $f stdout | tr -d \"\n \" | xclip -selection clipboard && rm $f'
  exit 0
fi

scrot -s -o -f "$SCREENSHOT_FILE" -e 'tesseract -l jpn $f stdout | tr -d \"\n \" | xclip -selection clipboard && rm $f'

