#!/bin/bash

noteFileName=$HOME/Documents/obsidian/daily-notes/$(date +%Y-%m-%d).md

if [ ! -f $noteFileName ]; then
  nvim -c "ObsidianToday" \
    -c "q"
fi

nvim -c "norm Go" \
  -c "norm o" \
  -c "norm Go## $(date +%H:%M)" \
  -c "norm o" \
  -c "startinsert" $noteFileName

