#!/usr/bin/env bash

CHOSEN_WPAPER="$1"


if [[ ! -e "$CHOSEN_WPAPER" ]]; then
    wpaper_folder=($HOME/Pictures/wallpapers)
    files=($wpaper_folder/*)

    let file_random_id=${RANDOM}%${#files[@]}
    CHOSEN_WPAPER=${files[$file_random_id]}
    echo "$CHOSEN_WPAPER"
fi

wal -n --saturate 1.2 --contrast 1.1 --cols16 -a 92 -i "$CHOSEN_WPAPER"
feh --bg-scale "$CHOSEN_WPAPER"

# set dunstrc symlink if it's not configured yet
[ -f "${HOME}/.config/dunst/dunstrc" ] || ln -s ${HOME}/.cache/wal/colors-pywal-dunstrc ${HOME}/.config/dunst/dunstrc

if pgrep -x 'dunst'; then
    pkill dunst && setsid dunst >/dev/null 2>&1 &
fi
