#!/usr/bin/env bash

wpaper_folder=($HOME/Pictures/wallpapers)

files=($wpaper_folder/*)

# echo "${files[0]}"
# echo "${files[1]}"
# echo "${#files[@]}"

let file_random_id=${RANDOM}%${#files[@]}

echo "${files[$file_random_id]}"

# nitrogen --head=0 --set-scaled "${files[$file_random_id]}"
# nitrogen --head=1 --set-scaled "${files[$file_random_id]}"

wal -n --cols16 -a 92 -i "${files[$file_random_id]}"
feh --bg-scale "${files[$file_random_id]}"
