#!/usr/bin/env bash

if [[ $# -eq 0 ]] then
  read -p "What is the name of the bash script you want to make? " file
  touch "$file" && chmod +x "$file" && echo '#!/usr/bin/env bash' >> "$file" && nvim "$file"
  exit 0
fi

touch "$1" && chmod +x "$1" && echo '#!/usr/bin/env bash' >> "$1" && nvim "$1"
exit 0

