# general.import = ["theme.toml"]
general.import = ["~/.cache/wal/colors-alacritty.toml"]

[window]
opacity = 0.85
blur = true # works only on macOS/KDE Wayland


[font.normal]
family = "my-chosen-font-family"

[keyboard]
bindings =  [
    { key = "Escape", command = { program = "/home/leore/dev/scripts/disable-caps" }},
    { key = "Escape", chars = "\u001b" },
]
